apiVersion: batch/v1
kind: CronJob
metadata:
  name: member-batch-job
  namespace: imhr
spec:
  schedule: "5,15,25,35,45,55 * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: member-batch
              image: imhrkr/batch-api:1.29
              env:
                - name: BATCH_JOB_NAME
                  value: memberJob
              envFrom:
                - configMapRef:
                    name: back-cm
          restartPolicy: OnFailure
      backoffLimit: 5
