apiVersion: batch/v1
kind: CronJob
metadata:
  name: rank-batch-job
  namespace: imhr
spec:
  schedule: "0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rank-batch
              image: imhrkr/batch-api:1.52
              env:
                - name: BATCH_JOB_NAME
                  value: rankJob
              envFrom:
                - configMapRef:
                    name: back-cm