apiVersion: batch/v1
kind: CronJob
metadata:
  name: rank-batch-job
  namespace: imhr
spec:
  schedule: "0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * *"
  startingDeadlineSeconds: 200  # ⬅️ 잡이 실행되지 못할 경우 허용 대기 시간 (선택)
  concurrencyPolicy: Forbid     # ⬅️ 이전 실행이 끝나지 않으면 중복 실행 금지
  successfulJobsHistoryLimit: 3 # ⬅️ 완료된 잡 기록 수 제한
  failedJobsHistoryLimit: 1     # ⬅️ 실패한 잡 기록 수 제한
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rank-batch
              image: imhrkr/batch-api:1.0
              env:
                - name: BATCH_JOB_NAME
                  value: rankJob
              envFrom:
                - configMapRef:
                    name: back-cm