apiVersion: batch/v1
kind: CronJob
metadata:
  name: score-batch-job
  namespace: imhr
spec:
  schedule: "*/4,*/8 * * * *"
  startingDeadlineSeconds: 40  # ⬅️ 잡이 실행되지 못할 경우 허용 대기 시간 (선택)
  concurrencyPolicy: Forbid     # ⬅️ 이전 실행이 끝나지 않으면 중복 실행 금지
  successfulJobsHistoryLimit: 1 # ⬅️ 완료된 잡 기록 수 제한
  failedJobsHistoryLimit: 1     # ⬅️ 실패한 잡 기록 수 제한
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: score-batch
              image: imhrkr/batch-api:1.54
              env:
                - name: BATCH_JOB_NAME
                  value: scoreJob
              envFrom:
                - configMapRef:
                    name: back-cm
