kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
spec:
  type: LoadBalancer
  selector:
    app: back-bluegreen
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30181
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
      nodePort: 30182